return {
    PACKET = 56,
    Enable = 1,
    Boss = {
        {ID = 309, Buff = 0, Debuff = 1, FullName = "Hell Maine" },
        {ID = 275, Buff = 0, Debuff = 1, FullName = "Kundun" },
        {ID = 700, Buff = 0, Debuff = 1, FullName = "Manticoras" },
		{ID = 702, Buff = 0, Debuff = 1, FullName = "Astelia" },
		{ID = 703, Buff = 0, Debuff = 1, FullName = "Anubis" },
		{ID = 704, Buff = 0, Debuff = 1, FullName = "Centauro" },
		{ID = 705, Buff = 0, Debuff = 1, FullName = "Lord Ferea" },
		{ID = 706, Buff = 0, Debuff = 1, FullName = "Wukong" },
		{ID = 707, Buff = 0, Debuff = 1, FullName = "Golem" },
		{ID = 55 , Buff = 0, Debuff = 1, FullName = "Death King" },
		{ID = 42 , Buff = 0, Debuff = 1, FullName = "Red Dragon" },
		{ID = 501, Buff = 0, Debuff = 1, FullName = "Great Golden Dragon" },
		{ID = 135, Buff = 0, Debuff = 1, FullName = "White Wizard" },
		{ID = 561, Buff = 1, Debuff = 0, FullName = "Medusa" },

		{ID = 710, Buff = 1, Debuff = 1, FullName = "Sylgroth" },
		{ID = 711, Buff = 1, Debuff = 1, FullName = "Solucius" },
		{ID = 712, Buff = 1, Debuff = 1, FullName = "Thar'bok" },
		{ID = 713, Buff = 1, Debuff = 1, FullName = "Grunthor" },
		{ID = 714, Buff = 1, Debuff = 1, FullName = "The Rock" },
		{ID = 715, Buff = 1, Debuff = 1, FullName = "Nargiluk" },
		{ID = 716, Buff = 1, Debuff = 1, FullName = "King Spider" },
		{ID = 717, Buff = 1, Debuff = 1, FullName = "Fulguito" },
		{ID = 718, Buff = 1, Debuff = 1, FullName = "Minus" },
		{ID = 719, Buff = 1, Debuff = 1, FullName = "Pedro" },
		{ID = 720, Buff = 1, Debuff = 1, FullName = "General Goblin" },
		{ID = 721, Buff = 1, Debuff = 1, FullName = "Valdrakar" },
		{ID = 722, Buff = 1, Debuff = 1, FullName = "Skeleton Warrior" },
		{ID = 723, Buff = 1, Debuff = 1, FullName = "King Minus" },
		{ID = 724, Buff = 1, Debuff = 1, FullName = "Rapitree" },


		{ID = 725, Buff = 1, Debuff = 0, FullName = "King Worm" },
		{ID = 726, Buff = 1, Debuff = 0, FullName = "Queen Spider" },
		{ID = 727, Buff = 1, Debuff = 0, FullName = "Belhemut" },
		{ID = 728, Buff = 1, Debuff = 0, FullName = "Sushiro" },
		{ID = 729, Buff = 1, Debuff = 0, FullName = "Kraggul" },
		{ID = 730, Buff = 1, Debuff = 0, FullName = "King Atlans" },
		{ID = 731, Buff = 1, Debuff = 0, FullName = "King Kanturu" },
		{ID = 732, Buff = 1, Debuff = 0, FullName = "Gobzila" },
		{ID = 733, Buff = 1, Debuff = 0, FullName = "Sucuwitch" },
		{ID = 734, Buff = 1, Debuff = 0, FullName = "Valtorion" },
		{ID = 735, Buff = 1, Debuff = 0, FullName = "Vorundel" },
		{ID = 736, Buff = 1, Debuff = 0, FullName = "Nyxarion" },
		{ID = 737, Buff = 1, Debuff = 0, FullName = "Redbat" },
		{ID = 738, Buff = 1, Debuff = 0, FullName = "Blacbat" },
		{ID = 739, Buff = 1, Debuff = 0, FullName = "Urdur" },
		{ID = 740, Buff = 1, Debuff = 0, FullName = "NX349" },
		{ID = 741, Buff = 1, Debuff = 0, FullName = "King Goblin" },
		{ID = 742, Buff = 1, Debuff = 0, FullName = "Spectro" },
		{ID = 743, Buff = 1, Debuff = 0, FullName = "Malzoron" },
		{ID = 744, Buff = 1, Debuff = 0, FullName = "Vermagoth" },
		{ID = 745, Buff = 1, Debuff = 0, FullName = "Assassin Spider" },
		{ID = 746, Buff = 1, Debuff = 0, FullName = "Wolford" },
		{ID = 747, Buff = 1, Debuff = 0, FullName = "Brizrabbit" },
		{ID = 748, Buff = 1, Debuff = 0, FullName = "Shadow Mage" },
		{ID = 749, Buff = 1, Debuff = 0, FullName = "Mutree" },
		{ID = 750, Buff = 1, Debuff = 0, FullName = "Zyrah" },
		{ID = 751, Buff = 1, Debuff = 0, FullName = "Venomous Zyrah" },
		{ID = 752, Buff = 1, Debuff = 0, FullName = "The Ruined King" },
		{ID = 753, Buff = 1, Debuff = 0, FullName = "Rocha" },
		{ID = 754, Buff = 1, Debuff = 0, FullName = "Beelee" },
		{ID = 755, Buff = 1, Debuff = 0, FullName = "Karalngola" },
		{ID = 756, Buff = 1, Debuff = 0, FullName = "Venomous Frog" },
		{ID = 757, Buff = 1, Debuff = 0, FullName = "Radio Frog" },
		{ID = 758, Buff = 1, Debuff = 0, FullName = "King Aida" },
		{ID = 759, Buff = 1, Debuff = 0, FullName = "Venomous Pud" },
		{ID = 760, Buff = 1, Debuff = 1, FullName = "Kentopeia" },
		{ID = 761, Buff = 1, Debuff = 0, FullName = "Crystal Worm" },
		{ID = 762, Buff = 1, Debuff = 0, FullName = "King Yeti" },
		

    }
}